Create testing workflow
Programmazione-per-la-Fisica/exercises pull request #15
Opened 2023-10-03 20:52 UTC by sbaldu

2024-02-18 18:58 UTC, giacomini commented
This PR should be rebased on main due to my recent changes

2024-02-18 19:00 UTC, giacomini requested changes

2024-02-19 14:41 UTC, sbaldu commented on .github/workflows/cmake-build.yml
> +      run: |
Done

2024-02-19 14:41 UTC, sbaldu commented on .github/workflows/cmake-build.yml
> +  BUILD_TYPE: Release
Done

2024-09-30 14:59 UTC, giacomini approved these changes

2024-09-30 14:59 UTC, merged